### ISSUE TITLE
Geofeed for non wireless subnets?

### ISSUE THREAD

**Issue by lpellegr** [Verizon/verizon-geofeed#7]
I am Laurent from Ipregistry, an IP geolocation provider. While checking for new geofeeds, I discovered this repository. Thank you for this initiative. We've added your geofeed to our pipeline.

However, we sometimes receive reports from your users about incorrect geolocation for some IPs. I was wondering if you have a geofeed, an API, or something that could assist us with the geolocation of non-wireless subnets that Verizon manages. We have processes in place to improve geolocation over time, but if you have something to share, this would make everyone happy.

If you prefer to share in private, I am reachable at [corrections@ipregistry.co](mailto:corrections@ipregistry.co).

**Comment by kpawlikowskivz** [comment]
Hello Laurent, thanks for reaching out! Our team is working on incorporating all Verizon owned IPs into this geo-feed in the near future. As we add different subnets outside of wireless, we will update the README file with the appropriate descriptions.

We will reach out to you via corrections@ipregistry.co to make sure we can address any specific concerns you may have.
